"""empty message

Revision ID: 2708ccf9390b
Revises: 82ed2813e359
Create Date: 2026-02-25 10:49:35.360612

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2708ccf9390b"
down_revision: Union[str, Sequence[str], None] = "82ed2813e359"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "memos",
    sa.Column(
      "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
    ),
    sa.Column("content", sa.String(), nullable=False),
    sa.Column("note", sa.String(), nullable=True),
    sa.Column("pinned", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False),
    sa.Column(
      "obfuscated", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False
    ),
    sa.Column("sercret", sa.BOOLEAN(), server_default=sa.text("true"), nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "memo_tags",
    sa.Column(
      "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
    ),
    sa.Column("memo_id", sa.UUID(), nullable=False),
    sa.Column("tag_id", sa.UUID(), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.ForeignKeyConstraint(["memo_id"], ["memos.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("memo_id", "tag_id", name="uq_memo_tag"),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("memo_tags")
  op.drop_table("memos")
  # ### end Alembic commands ###
