"""empty message

Revision ID: 2e32ed34d97c
Revises: 30c1f6aa924a
Create Date: 2026-01-28 09:50:59.016375

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e32ed34d97c"
down_revision: Union[str, Sequence[str], None] = "30c1f6aa924a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("users")
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "users",
    sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    sa.UniqueConstraint(
      "email",
      name=op.f("users_email_key"),
      postgresql_include=[],
      postgresql_nulls_not_distinct=False,
    ),
  )
  # ### end Alembic commands ###
