"""04

Revision ID: 306b0a3ae599
Revises: 9fab2fa36a41
Create Date: 2026-02-14 18:41:32.716772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "306b0a3ae599"
down_revision: Union[str, Sequence[str], None] = "9fab2fa36a41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  op.alter_column("users", "is_active", server_default=sa.text("true"))
  op.alter_column("users", "is_system", server_default=sa.text("false"))
  op.alter_column("users", "updated_at", server_default=sa.text("now()"))
  op.alter_column("auth_identities", "is_primary", server_default=sa.text("false"))
  op.alter_column("auth_identities", "updated_at", server_default=sa.text("now()"))
  op.alter_column("todos", "pinned", server_default=sa.text("false"))
  op.alter_column("todos", "done", server_default=sa.text("false"))
  op.alter_column("todos", "updated_at", server_default=sa.text("now()"))
  # Risky downtime-wise but...
  op.execute("ALTER TABLE todos ADD COLUMN tmp_priority INTEGER NOT NULL DEFAULT 0")
  op.execute("""
             UPDATE todos
             SET tmp_priority =
             CASE
                WHEN priority = 'low' THEN 1
                WHEN priority = 'medium' THEN 2
                WHEN priority = 'high' THEN 3
                WHEN priority = 'urgent' THEN 4
                ELSE 0
             END
             """)
  op.drop_column("todos", "priority")
  op.alter_column("todos", "tmp_priority", new_column_name="priority")
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column(
    "todos",
    "priority",
    existing_type=sa.Integer(),
    type_=postgresql.ENUM("none", "low", "medium", "high", "urgent", name="priority"),
    existing_nullable=False,
  )
  # ### end Alembic commands ###
