"""resetrm alembic/versions/*

Revision ID: 57747895bafa
Revises:
Create Date: 2026-02-04 10:30:34.840825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "57747895bafa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "users",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column(
      "user_type",
      sa.Enum("organization", "team", "individual", name="usertype"),
      nullable=False,
    ),
    sa.Column("parent_id", sa.UUID(), nullable=True),
    sa.Column("username", sa.String(), nullable=False),
    sa.Column("display_name", sa.String(), nullable=True),
    sa.Column("email", postgresql.CITEXT(), nullable=True),
    sa.Column("is_active", sa.BOOLEAN(), nullable=False),
    sa.Column("is_system", sa.BOOLEAN(), nullable=False),
    sa.Column("timezone", sa.String(), nullable=True),
    sa.Column("locale", sa.String(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["parent_id"], ["users.id"], ondelete="SET NULL"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_users_email"), table_name="users")
  op.drop_table("users")
  # ### end Alembic commands ###
