"""01

Revision ID: 79640d69efbd
Revises: c2655da4bfd0
Create Date: 2026-02-11 18:57:43.517276

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "79640d69efbd"
down_revision: Union[str, Sequence[str], None] = "c2655da4bfd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_index(
    "idx_auth_provider_uid",
    "auth_identities",
    ["provider", "provider_user_id"],
    unique=False,
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index("idx_auth_provider_uid", table_name="auth_identities")
  # ### end Alembic commands ###
