"""empty message

Revision ID: 805c3840b9f5
Revises: 2e32ed34d97c
Create Date: 2026-01-28 09:55:53.816268

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "805c3840b9f5"
down_revision: Union[str, Sequence[str], None] = "2e32ed34d97c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "users",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("username", sa.String(), nullable=False),
    sa.Column(
      "user_type",
      sa.Enum("auth_user", "organization", "team", "individual", name="usertype"),
      nullable=False,
    ),
    sa.Column("email", sa.String(), nullable=True),
    sa.Column("parent_id", sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(
      ["parent_id"],
      ["users.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_users_email"), table_name="users")
  op.drop_table("users")
  # ### end Alembic commands ###
