"""07

Revision ID: 82ed2813e359
Revises: 98d54f36ece2
Create Date: 2026-02-24 14:46:54.932132

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "82ed2813e359"
down_revision: Union[str, Sequence[str], None] = "98d54f36ece2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
  op.create_table(
    "contacts",
    sa.Column(
      "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
    ),
    sa.Column("name", sa.String(length=50), nullable=False),
    sa.Column("note", sa.String(), nullable=True),
    sa.Column("pinned", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "addresses",
    sa.Column(
      "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
    ),
    sa.Column("address", sa.String(length=255), nullable=False),
    sa.Column("contact_id", sa.UUID(), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "contact_tags",
    sa.Column(
      "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
    ),
    sa.Column("contact_id", sa.UUID(), nullable=False),
    sa.Column("tag_id", sa.UUID(), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("contact_id", "tag_id", name="uq_contact_tag"),
  )
  op.create_table(
    "emails",
    sa.Column(
      "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
    ),
    sa.Column("email", sa.String(length=50), nullable=False),
    sa.Column("contact_id", sa.UUID(), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "numbers",
    sa.Column(
      "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
    ),
    sa.Column("number", sa.String(length=50), nullable=False),
    sa.Column("contact_id", sa.UUID(), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.alter_column(
    "users",
    "email",
    existing_type=postgresql.CITEXT(),
    nullable=False,
  )
  bind = op.get_bind()
  inspector = sa.inspect(bind)
  for table in inspector.get_table_names():
    if table == "alembic_version":
      continue
    op.alter_column(
      table,
      "id",  # id existence is guarateed here so ...
      server_default=sa.text("gen_random_uuid()"),
    )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  raise Exception("Downgrade is forbidden.")
