"""empty message

Revision ID: 8823b1097958
Revises: b73e4b8a25a8
Create Date: 2026-03-16 17:00:02.475102

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8823b1097958"
down_revision: Union[str, Sequence[str], None] = "b73e4b8a25a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "memos",
    sa.Column("secret", sa.BOOLEAN(), server_default=sa.text("true"), nullable=False),
  )
  op.drop_column("memos", "sercret")
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  raise Exception("Downgrade is forbidden.")
