"""09

Revision ID: 98cecd1e554f
Revises: 2708ccf9390b
Create Date: 2026-03-02 16:32:14.541601

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98cecd1e554f"
down_revision: Union[str, Sequence[str], None] = "2708ccf9390b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "shared_todos",
    sa.Column(
      "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
    ),
    sa.Column("todo_id", sa.UUID(), nullable=False),
    sa.Column("shared_user_id", sa.UUID(), nullable=False),
    sa.Column(
      "permissions",
      sa.Enum("R", "W", name="permission"),
      server_default=sa.text("'R'::permission"),
      nullable=False,
    ),
    sa.Column(
      "recursive", sa.BOOLEAN(), server_default=sa.text("true"), nullable=False
    ),
    sa.Column("expiration", sa.DateTime(timezone=True), nullable=True),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.ForeignKeyConstraint(["shared_user_id"], ["users.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["todo_id"], ["todos.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("todo_id", "shared_user_id", name="uq_todo_shared_user"),
  )
  op.create_index(
    "idx_shared_todos_shared_user_id", "shared_todos", ["shared_user_id"], unique=False
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index("idx_shared_todos_shared_user_id", table_name="shared_todos")
  op.drop_table("shared_todos")
  # ### end Alembic commands ###
