"""06

Revision ID: 98d54f36ece2
Revises: fc15d7e3cc44
Create Date: 2026-02-17 17:49:12.300702

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98d54f36ece2"
down_revision: Union[str, Sequence[str], None] = "fc15d7e3cc44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "tags",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("name", sa.String(length=50), nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "todo_tags",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("todo_id", sa.UUID(), nullable=False),
    sa.Column("tag_id", sa.UUID(), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["todo_id"], ["todos.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("todo_id", "tag_id", name="uq_todo_tag"),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("todo_tags")
  op.drop_table("tags")
  # ### end Alembic commands ###
