"""02

Revision ID: 99ff4a460070
Revises: 79640d69efbd
Create Date: 2026-02-11 19:08:10.060720

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99ff4a460070"
down_revision: Union[str, Sequence[str], None] = "79640d69efbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("idx_auth_provider_uid"), table_name="auth_identities")
  op.create_index(
    "idx_auth_provider_uid",
    "auth_identities",
    ["provider", "provider_user_id"],
    unique=True,
    postgresql_where=sa.text("provider_user_id IS NOT NULL"),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(
    "idx_auth_provider_uid",
    table_name="auth_identities",
    postgresql_where=sa.text("provider_user_id IS NOT NULL"),
  )
  op.create_index(
    op.f("idx_auth_provider_uid"),
    "auth_identities",
    ["provider", "provider_user_id"],
    unique=False,
  )
  # ### end Alembic commands ###
