"""empty message

Revision ID: 9fab2fa36a41
Revises: 99ff4a460070
Create Date: 2026-02-14 17:43:34.845094

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9fab2fa36a41"
down_revision: Union[str, Sequence[str], None] = "99ff4a460070"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "todos",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("title", sa.String(length=200), nullable=False),
    sa.Column(
      "priority",
      sa.Enum("none", "low", "medium", "high", "urgent", name="priority"),
      nullable=False,
    ),
    sa.Column("pinned", sa.BOOLEAN(), nullable=False),
    sa.Column("done", sa.BOOLEAN(), nullable=False),
    sa.Column("description", sa.String(), nullable=True),
    sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("parent_id", sa.UUID(), nullable=True),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["parent_id"], ["todos.id"], ondelete="SET NULL"),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("todos")
  # ### end Alembic commands ###
