"""empty message

Revision ID: b73e4b8a25a8
Revises: 98cecd1e554f
Create Date: 2026-03-06 14:36:45.390774

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "b73e4b8a25a8"
down_revision: Union[str, Sequence[str], None] = "98cecd1e554f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# NOTE: don't create the type if exists, pg ENUM better for if-exists detection in alembic
permission_enum = postgresql.ENUM("R", "W", name="permission", create_type=False)


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "shared_contacts",
    sa.Column(
      "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
    ),
    sa.Column("contact_id", sa.UUID(), nullable=False),
    sa.Column("shared_user_id", sa.UUID(), nullable=False),
    sa.Column(
      "permissions",
      permission_enum,
      server_default=sa.text("'R'::permission"),
      nullable=False,
    ),
    sa.Column("expiration", sa.DateTime(timezone=True), nullable=True),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["shared_user_id"], ["users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("contact_id", "shared_user_id", name="uq_contact_shared_user"),
  )
  op.create_index(
    "idx_shared_contacts_shared_user_id",
    "shared_contacts",
    ["shared_user_id"],
    unique=False,
  )
  op.create_table(
    "shared_memos",
    sa.Column(
      "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
    ),
    sa.Column("memo_id", sa.UUID(), nullable=False),
    sa.Column("shared_user_id", sa.UUID(), nullable=False),
    sa.Column(
      "permissions",
      permission_enum,
      server_default=sa.text("'R'::permission"),
      nullable=False,
    ),
    sa.Column("expiration", sa.DateTime(timezone=True), nullable=True),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.ForeignKeyConstraint(["memo_id"], ["memos.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["shared_user_id"], ["users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("memo_id", "shared_user_id", name="uq_memo_shared_user"),
  )
  op.create_index(
    "idx_shared_memos_shared_user_id", "shared_memos", ["shared_user_id"], unique=False
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index("idx_shared_memos_shared_user_id", table_name="shared_memos")
  op.drop_table("shared_memos")
  op.drop_index("idx_shared_contacts_shared_user_id", table_name="shared_contacts")
  op.drop_table("shared_contacts")
  # ### end Alembic commands ###
