"""init

Revision ID: c2655da4bfd0
Revises:
Create Date: 2026-02-11 18:03:11.545539

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c2655da4bfd0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  op.execute("CREATE EXTENSION IF NOT EXISTS citext")

  op.create_table(
    "users",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column(
      "user_type",
      sa.Enum("organization", "team", "individual", name="user_type"),
      nullable=False,
    ),
    sa.Column("parent_id", sa.UUID(), nullable=True),
    sa.Column("username", sa.String(), nullable=False),
    sa.Column("display_name", sa.String(), nullable=True),
    sa.Column("email", postgresql.CITEXT(), nullable=True),
    sa.Column("is_active", sa.BOOLEAN(), nullable=False),
    sa.Column("is_system", sa.BOOLEAN(), nullable=False),
    sa.Column("timezone", sa.String(), nullable=True),
    sa.Column("locale", sa.String(), nullable=True),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["parent_id"], ["users.id"], ondelete="SET NULL"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
  op.create_table(
    "auth_identities",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column(
      "provider",
      sa.Enum("password", "google", "apple", name="provider"),
      nullable=False,
    ),
    sa.Column("provider_user_id", sa.String(), nullable=True),
    sa.Column("password_hash", sa.String(), nullable=True),
    sa.Column("email", postgresql.CITEXT(), nullable=True),
    sa.Column("is_primary", sa.BOOLEAN(), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint(
      "(email IS NOT NULL AND password_hash IS NOT NULL) OR (provider IS NOT NULL AND provider_user_id IS NOT NULL)",
      name="auth_identity_check",
    ),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("auth_identities")
  op.drop_index(op.f("ix_users_email"), table_name="users")
  op.drop_table("users")
  # ### end Alembic commands ###
