"""init users schema

Revision ID: d090196ab849
Revises:
Create Date: 2026-02-04 10:20:33.995563

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d090196ab849"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("users", sa.Column("display_name", sa.String(), nullable=True))
  op.add_column("users", sa.Column("is_active", sa.BOOLEAN(), nullable=False))
  op.add_column("users", sa.Column("is_system", sa.BOOLEAN(), nullable=False))
  op.add_column("users", sa.Column("timezone", sa.String(), nullable=True))
  op.add_column("users", sa.Column("locale", sa.String(), nullable=True))
  op.add_column(
    "users", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
  )
  op.add_column(
    "users", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)
  )
  op.add_column(
    "users", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
  )
  op.alter_column(
    "users", "id", existing_type=sa.INTEGER(), type_=sa.UUID(), existing_nullable=False
  )
  op.alter_column(
    "users",
    "parent_id",
    existing_type=sa.INTEGER(),
    type_=sa.UUID(),
    existing_nullable=True,
  )
  op.alter_column(
    "users",
    "email",
    existing_type=sa.VARCHAR(),
    type_=postgresql.CITEXT(),
    existing_nullable=True,
  )
  op.drop_constraint(op.f("users_parent_id_fkey"), "users", type_="foreignkey")
  op.create_foreign_key(
    None, "users", "users", ["parent_id"], ["id"], ondelete="SET NULL"
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint(None, "users", type_="foreignkey")
  op.create_foreign_key(
    op.f("users_parent_id_fkey"), "users", "users", ["parent_id"], ["id"]
  )
  op.alter_column(
    "users",
    "email",
    existing_type=postgresql.CITEXT(),
    type_=sa.VARCHAR(),
    existing_nullable=True,
  )
  op.alter_column(
    "users",
    "parent_id",
    existing_type=sa.UUID(),
    type_=sa.INTEGER(),
    existing_nullable=True,
  )
  op.alter_column(
    "users", "id", existing_type=sa.UUID(), type_=sa.INTEGER(), existing_nullable=False
  )
  op.drop_column("users", "deleted_at")
  op.drop_column("users", "updated_at")
  op.drop_column("users", "created_at")
  op.drop_column("users", "locale")
  op.drop_column("users", "timezone")
  op.drop_column("users", "is_system")
  op.drop_column("users", "is_active")
  op.drop_column("users", "display_name")
  # ### end Alembic commands ###
