"""05

Revision ID: fc15d7e3cc44
Revises: 306b0a3ae599
Create Date: 2026-02-14 21:03:24.413935

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fc15d7e3cc44"
down_revision: Union[str, Sequence[str], None] = "306b0a3ae599"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "todo_recurrences",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("todo_id", sa.UUID(), nullable=False),
    sa.Column("recurrence_type", sa.Integer(), nullable=True),
    sa.Column("interval", sa.Integer(), nullable=True),
    sa.Column("days_of_week", postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column("days_of_month", postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column("weeks_of_month", postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column("months_of_year", postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column(
      "created_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(timezone=True),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.CheckConstraint(
      "\n      (\n        recurrence_type IS NULL\n        AND interval IS NULL\n        AND days_of_week IS NULL\n        AND days_of_month IS NULL\n        AND weeks_of_month IS NULL\n        AND months_of_year IS NULL\n      )\n      OR\n      (\n        recurrence_type IS NOT NULL\n        AND interval IS NOT NULL\n        AND\n        (\n          (\n            days_of_week IS NULL\n            AND days_of_month IS NULL\n            AND weeks_of_month IS NULL\n            AND months_of_year IS NULL\n          )\n          OR\n          (\n            (days_of_week IS NOT NULL)::int +\n            (days_of_month IS NOT NULL)::int +\n            (weeks_of_month IS NOT NULL)::int +\n            (months_of_year IS NOT NULL)::int\n          ) = 1\n        )\n      )\n      ",
      name="todo_recurrence_check",
    ),
    sa.ForeignKeyConstraint(["todo_id"], ["todos.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("todo_id"),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("todo_recurrences")
  # ### end Alembic commands ###
